#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PT_Plugins
{
	
	
	/// <summary>
	/// Status of the Projet
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum pt_projet_statecode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Inactive = 1,
	}
	
	/// <summary>
	/// Reason for the status of the Projet
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum pt_projet_statuscode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Inactive = 2,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("pt_projet")]
	public partial class pt_Projet : Microsoft.Xrm.Sdk.Entity
	{
		
		/// <summary>
		/// Default Constructor.
		/// </summary>
		public pt_Projet() : 
				base(EntityLogicalName)
		{
		}
		
		public const string EntityLogicalName = "pt_projet";
		
		public const string EntityLogicalCollectionName = "pt_projets";
		
		public const string EntitySetName = "pt_projets";
		
		/// <summary>
		/// Unique identifier of the user who created the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdby");
			}
		}
		
		/// <summary>
		/// Date and time when the record was created.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdon")]
		public System.Nullable<System.DateTime> CreatedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("createdon");
			}
		}
		
		/// <summary>
		/// Unique identifier of the delegate user who created the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedOnBehalfBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdonbehalfby");
			}
		}
		
		/// <summary>
		/// Sequence number of the import that created this record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("importsequencenumber")]
		public System.Nullable<int> ImportSequenceNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("importsequencenumber");
			}
			set
			{
				this.SetAttributeValue("importsequencenumber", value);
			}
		}
		
		/// <summary>
		/// Unique identifier of the user who modified the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedby");
			}
		}
		
		/// <summary>
		/// Date and time when the record was modified.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedon")]
		public System.Nullable<System.DateTime> ModifiedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("modifiedon");
			}
		}
		
		/// <summary>
		/// Unique identifier of the delegate user who modified the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedOnBehalfBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedonbehalfby");
			}
		}
		
		/// <summary>
		/// Date and time that the record was migrated.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("overriddencreatedon")]
		public System.Nullable<System.DateTime> OverriddenCreatedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("overriddencreatedon");
			}
			set
			{
				this.SetAttributeValue("overriddencreatedon", value);
			}
		}
		
		/// <summary>
		/// Owner Id
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ownerid")]
		public Microsoft.Xrm.Sdk.EntityReference OwnerId
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("ownerid");
			}
			set
			{
				this.SetAttributeValue("ownerid", value);
			}
		}
		
		/// <summary>
		/// Unique identifier for the business unit that owns the record
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningbusinessunit")]
		public Microsoft.Xrm.Sdk.EntityReference OwningBusinessUnit
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningbusinessunit");
			}
		}
		
		/// <summary>
		/// Unique identifier for the team that owns the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningteam")]
		public Microsoft.Xrm.Sdk.EntityReference OwningTeam
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningteam");
			}
		}
		
		/// <summary>
		/// Unique identifier for the user that owns the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
		public Microsoft.Xrm.Sdk.EntityReference OwningUser
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owninguser");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("pt_budgetheures")]
		public System.Nullable<decimal> pt_BudgetHeures
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<decimal>>("pt_budgetheures");
			}
			set
			{
				this.SetAttributeValue("pt_budgetheures", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("pt_chefdeprojet")]
		public Microsoft.Xrm.Sdk.EntityReference pt_Chefdeprojet
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("pt_chefdeprojet");
			}
			set
			{
				this.SetAttributeValue("pt_chefdeprojet", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("pt_clientid")]
		public Microsoft.Xrm.Sdk.EntityReference pt_ClientID
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("pt_clientid");
			}
			set
			{
				this.SetAttributeValue("pt_clientid", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("pt_datededebut")]
		public System.Nullable<System.DateTime> pt_Datededebut
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("pt_datededebut");
			}
			set
			{
				this.SetAttributeValue("pt_datededebut", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("pt_datedefin")]
		public System.Nullable<System.DateTime> pt_Datedefin
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("pt_datedefin");
			}
			set
			{
				this.SetAttributeValue("pt_datedefin", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("pt_description")]
		public string pt_Description
		{
			get
			{
				return this.GetAttributeValue<string>("pt_description");
			}
			set
			{
				this.SetAttributeValue("pt_description", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("pt_name")]
		public string pt_Name
		{
			get
			{
				return this.GetAttributeValue<string>("pt_name");
			}
			set
			{
				this.SetAttributeValue("pt_name", value);
			}
		}
		
		/// <summary>
		/// Unique identifier for entity instances
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("pt_projetid")]
		public System.Nullable<System.Guid> pt_ProjetId
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("pt_projetid");
			}
			set
			{
				this.SetAttributeValue("pt_projetid", value);
				if (value.HasValue)
				{
					base.Id = value.Value;
				}
				else
				{
					base.Id = System.Guid.Empty;
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("pt_projetid")]
		public override System.Guid Id
		{
			get
			{
				return base.Id;
			}
			set
			{
				this.pt_ProjetId = value;
			}
		}
		
		/// <summary>
		/// Permet d'avoir le nombre d'heures totales que doit prendre toutes les tâches. Permet de comparer avec le budget accordé au projet
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("pt_rollupheurestotalesdetouteslestaches")]
		public System.Nullable<decimal> pt_Rollupheurestotalesdetouteslestaches
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<decimal>>("pt_rollupheurestotalesdetouteslestaches");
			}
		}
		
		/// <summary>
		/// Last Updated time of rollup field Heures totales de toutes les tâches.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("pt_rollupheurestotalesdetouteslestaches_date")]
		public System.Nullable<System.DateTime> pt_Rollupheurestotalesdetouteslestaches_Date
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("pt_rollupheurestotalesdetouteslestaches_date");
			}
		}
		
		/// <summary>
		/// State of rollup field Heures totales de toutes les tâches.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("pt_rollupheurestotalesdetouteslestaches_state")]
		public System.Nullable<int> pt_Rollupheurestotalesdetouteslestaches_State
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("pt_rollupheurestotalesdetouteslestaches_state");
			}
		}
		
		/// <summary>
		/// Status of the Projet
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statecode")]
		public virtual pt_projet_statecode? statecode
		{
			get
			{
				return ((pt_projet_statecode?)(EntityOptionSetEnum.GetEnum(this, "statecode")));
			}
			set
			{
				this.SetAttributeValue("statecode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		/// <summary>
		/// Reason for the status of the Projet
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statuscode")]
		public virtual pt_projet_statuscode? statuscode
		{
			get
			{
				return ((pt_projet_statuscode?)(EntityOptionSetEnum.GetEnum(this, "statuscode")));
			}
			set
			{
				this.SetAttributeValue("statuscode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		/// <summary>
		/// For internal use only.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timezoneruleversionnumber")]
		public System.Nullable<int> TimeZoneRuleVersionNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("timezoneruleversionnumber");
			}
			set
			{
				this.SetAttributeValue("timezoneruleversionnumber", value);
			}
		}
		
		/// <summary>
		/// Time zone code that was in use when the record was created.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("utcconversiontimezonecode")]
		public System.Nullable<int> UTCConversionTimeZoneCode
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("utcconversiontimezonecode");
			}
			set
			{
				this.SetAttributeValue("utcconversiontimezonecode", value);
			}
		}
		
		/// <summary>
		/// Version Number
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("versionnumber")]
		public System.Nullable<long> VersionNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<long>>("versionnumber");
			}
		}
		
		/// <summary>
		/// 1:N pt_tache_ProjetID_pt_projet
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("pt_tache_ProjetID_pt_projet")]
		public System.Collections.Generic.IEnumerable<PT_Plugins.pt_Tache> pt_tache_ProjetID_pt_projet
		{
			get
			{
				return this.GetRelatedEntities<PT_Plugins.pt_Tache>("pt_tache_ProjetID_pt_projet", null);
			}
			set
			{
				this.SetRelatedEntities<PT_Plugins.pt_Tache>("pt_tache_ProjetID_pt_projet", null, value);
			}
		}
	}
}
#pragma warning restore CS1591
