#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: Microsoft.Xrm.Sdk.Client.ProxyTypesAssemblyAttribute()]

namespace PT_Plugins
{
	
	
	/// <summary>
	/// Represents a source of entities bound to a Dataverse service. It tracks and manages changes made to the retrieved entities.
	/// </summary>
	public partial class OrgContext : Microsoft.Xrm.Sdk.Client.OrganizationServiceContext
	{
		
		/// <summary>
		/// Constructor.
		/// </summary>
		public OrgContext(Microsoft.Xrm.Sdk.IOrganizationService service) : 
				base(service)
		{
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="PT_Plugins.pt_Projet"/> entities.
		/// </summary>
		public System.Linq.IQueryable<PT_Plugins.pt_Projet> pt_ProjetSet
		{
			get
			{
				return this.CreateQuery<PT_Plugins.pt_Projet>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="PT_Plugins.pt_Tache"/> entities.
		/// </summary>
		public System.Linq.IQueryable<PT_Plugins.pt_Tache> pt_TacheSet
		{
			get
			{
				return this.CreateQuery<PT_Plugins.pt_Tache>();
			}
		}
	}
}
#pragma warning restore CS1591
